### ISSUE TITLE
Not sure which image is the wrapperest

### ISSUE THREAD

**Issue by jory** [btford/wrapgeni.us#7]
![img_20140210_121512](https://f.cloud.github.com/assets/200687/2128344/d7486f66-9279-11e3-806f-c2595f056652.jpg)
![img_20140210_121626](https://f.cloud.github.com/assets/200687/2128345/d74951d8-9279-11e3-9e40-ecd67aa14c07.jpg)
![img_20140210_121946](https://f.cloud.github.com/assets/200687/2128346/d7499a08-9279-11e3-9b52-faa1a774a210.jpg)

**Comment by operatorjen** [comment]
third is cool

**Comment by btford** [comment]
vote for 3
